//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2020 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ListPublishingProfileXMLWithSecrets) DeepCopyInto(out *ListPublishingProfileXMLWithSecrets) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListPublishingProfileXMLWithSecrets.
func (in *ListPublishingProfileXMLWithSecrets) DeepCopy() *ListPublishingProfileXMLWithSecrets {
	if in == nil {
		return nil
	}
	out := new(ListPublishingProfileXMLWithSecrets)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ListPublishingProfileXMLWithSecrets) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ListPublishingProfileXMLWithSecretsList) DeepCopyInto(out *ListPublishingProfileXMLWithSecretsList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ListPublishingProfileXMLWithSecrets, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListPublishingProfileXMLWithSecretsList.
func (in *ListPublishingProfileXMLWithSecretsList) DeepCopy() *ListPublishingProfileXMLWithSecretsList {
	if in == nil {
		return nil
	}
	out := new(ListPublishingProfileXMLWithSecretsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ListPublishingProfileXMLWithSecretsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ListPublishingProfileXMLWithSecretsObservation) DeepCopyInto(out *ListPublishingProfileXMLWithSecretsObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListPublishingProfileXMLWithSecretsObservation.
func (in *ListPublishingProfileXMLWithSecretsObservation) DeepCopy() *ListPublishingProfileXMLWithSecretsObservation {
	if in == nil {
		return nil
	}
	out := new(ListPublishingProfileXMLWithSecretsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ListPublishingProfileXMLWithSecretsParameters) DeepCopyInto(out *ListPublishingProfileXMLWithSecretsParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListPublishingProfileXMLWithSecretsParameters.
func (in *ListPublishingProfileXMLWithSecretsParameters) DeepCopy() *ListPublishingProfileXMLWithSecretsParameters {
	if in == nil {
		return nil
	}
	out := new(ListPublishingProfileXMLWithSecretsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ListPublishingProfileXMLWithSecretsSpec) DeepCopyInto(out *ListPublishingProfileXMLWithSecretsSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	out.ForProvider = in.ForProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListPublishingProfileXMLWithSecretsSpec.
func (in *ListPublishingProfileXMLWithSecretsSpec) DeepCopy() *ListPublishingProfileXMLWithSecretsSpec {
	if in == nil {
		return nil
	}
	out := new(ListPublishingProfileXMLWithSecretsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ListPublishingProfileXMLWithSecretsStatus) DeepCopyInto(out *ListPublishingProfileXMLWithSecretsStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListPublishingProfileXMLWithSecretsStatus.
func (in *ListPublishingProfileXMLWithSecretsStatus) DeepCopy() *ListPublishingProfileXMLWithSecretsStatus {
	if in == nil {
		return nil
	}
	out := new(ListPublishingProfileXMLWithSecretsStatus)
	in.DeepCopyInto(out)
	return out
}
