apiVersion: armappservice.azureextra.crossplane.io/v1alpha1
kind: ListPublishingProfileXMLWithSecrets
metadata:
  name: publishingprofilexmlwithsecretsmsfmipagoapi2cert
spec:
  forProvider:
    resource_group_name: rg-mipago-cert
    app_service_name: msf-mipago-api2-cert
  writeConnectionSecretToRef:
    namespace: crossplane-system
    name:  publishingprofilexmlwithsecretsmsfmipagoapi2cert
